### PR TITLE
Bug fix + some features proposal

### PR DESCRIPTION
**Pull request by foolsbazar**
I changed the annoying behaviour of the microphone button, I reduced the number of entries in the pull down menu when the keyboard is open in order to make it more usable and I fixed one bug with the audio notes upload.

### CODE REVIEW

**Comment by foolsbazar** [comment]
I added the possibility to see images in channel with the biggest height or width possible. As it is done in telegram X.

I don't know how to deal with qstr() so the button in AppearencePage.qml has to be reviewed.

**Comment by Thaodan** [comment]
iinstead of reverting you can rebase and edit your commits .
also you can smash the 4 commits before your comment and make them into one .

**Comment by foolsbazar** [comment]
> iinstead of reverting you can rebase and edit your commits .
> also you can smash the 4 commits before your comment and make them into one .
Thanks for pointing this out.  I was too lazy to understand how to do it back then.  Now i'm finding infos only on how to smash the lasts commits, i'm not getting how to modify a specific part of the history.

**Comment by Thaodan** [comment]
Try to search for git rebase --
interactive.
If you use emacs there's magit which 
makes this very painless.

**Comment by blacksailer** [comment]
Hi! Thanks for pull request. You've changed mic slide to the side is it better? And I will add padding when pictures is full sized, padding Theme.horizontalPageMargin on the left and right must be for clean ui.

**Pull request merged**
